name: ticketing-system
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - JWT_KEY=your_jwt_secret_key
      - DATABASE_URL=postgresql://auth_user:password123@host.docker.internal:5432/auth_service
    networks:
      - ticketing-network

  ticket-service:
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    environment:
      - JWT_KEY=your_jwt_secret_key
      - DATABASE_URL=postgresql://ticket_user:password123@host.docker.internal:5432/ticket_service
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
      - KAFKA_CLIENT_ID=ticket-service
      - KAFKA_GROUP_ID=ticket-service-group
    networks:
      - ticketing-network
    depends_on:
      - auth-service

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      - JWT_KEY=your_jwt_secret_key
      - DATABASE_URL=postgresql://order_user:password123@host.docker.internal:5432/order_service
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
      - KAFKA_CLIENT_ID=order-service
      - KAFKA_GROUP_ID=order-service-group
    networks:
      - ticketing-network
    depends_on:
      - auth-service
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - auth-service
      - ticket-service
      - order-service

networks:
  ticketing-network:
    external: true
